export const projectsData = [
  // Chettinad Project (52 images from Google Drive)
  { title: "Chettinad 1", type: "image", link: "https://drive.google.com/file/d/1E4aV0esAqCvZMNwS_0GCHBVEiTQepxiL/preview" },
  { title: "Chettinad 2", type: "image", link: "https://drive.google.com/file/d/113fSmWtoVohcEnhuYEHJ3mRRrQs5N__7/preview" },
  { title: "Chettinad 3", type: "image", link: "https://drive.google.com/file/d/11gItRnzoDbsQ1obGmdK_GH0u0dZrpByN/preview" },
  { title: "Chettinad 4", type: "image", link: "https://drive.google.com/file/d/12FBHCYQysB4Jzn-PK3voPEFnSPcKs_Ql/preview" },
  { title: "Chettinad 5", type: "image", link: "https://drive.google.com/file/d/12XV3bJ_lKbmJUbDzl3vDVEU29sqr1ztW/preview" },
  { title: "Chettinad 6", type: "image", link: "https://drive.google.com/file/d/14UGT23d8t7WWlfMRAOLwPYIG5PjeHQlj/preview" },
  { title: "Chettinad 7", type: "image", link: "https://drive.google.com/file/d/175eK-1yCBnLfFqi_RLVm-yLCajLWF3wq/preview" },
  { title: "Chettinad 8", type: "image", link: "https://drive.google.com/file/d/17zR5ezM8OdaNh_md1MPBjs9vPd-h0cth/preview" },
  { title: "Chettinad 9", type: "image", link: "https://drive.google.com/file/d/18T_PZFKFgSNidWuRpNzSm6f_AqMO_DYD/preview" },
  { title: "Chettinad 10", type: "image", link: "https://drive.google.com/file/d/1CWwOpRMraG0ArQYppoOsefOyQ2o5TCIs/preview" },
  { title: "Chettinad 11", type: "image", link: "https://drive.google.com/file/d/1CcvRhIFUwW9BmEMZhi9t3YsFmswklh7o/preview" },
  { title: "Chettinad 12", type: "image", link: "https://drive.google.com/file/d/1DBnUsM8-cdl3dnxQa9UQPBXRJMJy5081/preview" },
  { title: "Chettinad 13", type: "image", link: "https://drive.google.com/file/d/1G7gjh4gnqJ6B3XGHxeRi2EpRnV9gNdOB/preview" },
  { title: "Chettinad 14", type: "image", link: "https://drive.google.com/file/d/1H9XPJfG1MBZCYa8GQth1yPnITJRHXBVL/preview" },
  { title: "Chettinad 15", type: "image", link: "https://drive.google.com/file/d/1JNHYEZAzhrGEyoWohaPv1yDedYvvBLxQ/preview" },
  { title: "Chettinad 16", type: "image", link: "https://drive.google.com/file/d/1JpJNQ-qS4bjyZKK0PBGLWGmq03CaWwiP/preview" },
  { title: "Chettinad 17", type: "image", link: "https://drive.google.com/file/d/1LF9lU0a5x9MPwoXb8nme7MQYmjRtjCDW/preview" },
  { title: "Chettinad 18", type: "image", link: "https://drive.google.com/file/d/1MN6loncyn7ws6aGGIQUDSs-4LlumQNdG/preview" },
  { title: "Chettinad 19", type: "image", link: "https://drive.google.com/file/d/1NQY---9ztzrsR1zkplnhm9vpMcyVAlRg/preview" },
  { title: "Chettinad 20", type: "image", link: "https://drive.google.com/file/d/1PRHnfbUi9o5MgBgnrTzvYWA-JHDF23HV/preview" },
  { title: "Chettinad 21", type: "image", link: "https://drive.google.com/file/d/1SVVtXYHVKmAra1cIt8dTDJ4xhOMvMCT8/preview" },
  { title: "Chettinad 22", type: "image", link: "https://drive.google.com/file/d/1SapQjNZ55I8ckZ9ZK7XBrbsH3IgDbm81/preview" },
  { title: "Chettinad 23", type: "image", link: "https://drive.google.com/file/d/1Sl01REDLkPeDhIu0GU_g3m2zmgdKmlrp/preview" },
  { title: "Chettinad 24", type: "image", link: "https://drive.google.com/file/d/1VkpNMEZBYrXXRAnR2dhKrhjw_k3WGYsF/preview" },
  { title: "Chettinad 25", type: "image", link: "https://drive.google.com/file/d/1WUkzVpUZt5CG2Xj1suZd-i1Lu768GEAv/preview" },
  { title: "Chettinad 26", type: "image", link: "https://drive.google.com/file/d/1Wa_3hnBiWDffUpB86WyrydKv3-oDZGra/preview" },
  { title: "Chettinad 27", type: "image", link: "https://drive.google.com/file/d/1Y3j5KJYCPRBtb7hvXiOwxXB7z6tcxnGz/preview" },
  { title: "Chettinad 28", type: "image", link: "https://drive.google.com/file/d/1ZI-jLdwNi_mSccNO23kxPnI_s88jU7DS/preview" },
  { title: "Chettinad 29", type: "image", link: "https://drive.google.com/file/d/1abJjBkesTYgecEbrDML1gdUSxexiAfku/preview" },
  { title: "Chettinad 30", type: "image", link: "https://drive.google.com/file/d/1ckShrdY_JX7GvJgjRqC8INk5Y1fT_J1y/preview" },
  { title: "Chettinad 31", type: "image", link: "https://drive.google.com/file/d/1eq4GK7j2dpD9RWgAwTrVT6wcgDaR-tsE/preview" },
  { title: "Chettinad 32", type: "image", link: "https://drive.google.com/file/d/1heoVCLnpDkdRYv2cOW6BnLFL_HdLjaCy/preview" },
  { title: "Chettinad 33", type: "image", link: "https://drive.google.com/file/d/1i94p9r73QT34IvFytEBtWV6GHm-z3cDX/preview" },
  { title: "Chettinad 34", type: "image", link: "https://drive.google.com/file/d/1ixwaFeqzaQ0FjJ1aZAGLPPy4SJau-9eK/preview" },
  { title: "Chettinad 35", type: "image", link: "https://drive.google.com/file/d/1mrLuig9zn1okhuBZauQxTrtpTIE0PqW5/preview" },
  { title: "Chettinad 36", type: "image", link: "https://drive.google.com/file/d/1nHCCC1SovCqFhFtRHLZsWW59__eYHFtM/preview" },
  { title: "Chettinad 37", type: "image", link: "https://drive.google.com/file/d/1nLMEX1cdoekEZRt1SJL4r2iJhfdpvrVG/preview" },
  { title: "Chettinad 38", type: "image", link: "https://drive.google.com/file/d/1neAVfblcWmggnguoAoWpSqVv63Hs7_uF/preview" },
  { title: "Chettinad 39", type: "image", link: "https://drive.google.com/file/d/1oGMdCQtyXcEaBY_PFfbekKVggsVS0Fn8/preview" },
  { title: "Chettinad 40", type: "image", link: "https://drive.google.com/file/d/1p9hoQr65UoqGMEQ_VJ6_wTvfefHZ1Xi0/preview" },
  { title: "Chettinad 41", type: "image", link: "https://drive.google.com/file/d/1pN1a2_Yie7F393lDUOxxgdVJsCaadQrm/preview" },
  { title: "Chettinad 42", type: "image", link: "https://drive.google.com/file/d/1plMJ1AunRI2nrvDjC7zKXTk8kqDBve6h/preview" },
  { title: "Chettinad 43", type: "image", link: "https://drive.google.com/file/d/1qG-Qk_ljSAqHPo6cp_gF0VQ7cNiRvV4n/preview" },
  { title: "Chettinad 44", type: "image", link: "https://drive.google.com/file/d/1rbBB7y9EepYA5YpzQILCLtCfL2KNqMhy/preview" },
  { title: "Chettinad 45", type: "image", link: "https://drive.google.com/file/d/1tXH4oEB54piqxNFz7qWEwsfaff45ZB5D/preview" },
  { title: "Chettinad 46", type: "image", link: "https://drive.google.com/file/d/1v0GGNrDqK9-QmNk-5edB5ZK6w3b4UdCk/preview" },
  { title: "Chettinad 47", type: "image", link: "https://drive.google.com/file/d/1wFpI0Oy6-hmO6P570T9FaO4FbDqdVF47/preview" },
  { title: "Chettinad 48", type: "image", link: "https://drive.google.com/file/d/1x6DleiDgMGlZoc6apdhdBiENQZ-zEHNI/preview" },
  { title: "Chettinad 49", type: "image", link: "https://drive.google.com/file/d/1xGfOEiuLFIDEqU93g3zbaGzWxKvkudf5/preview" },
  { title: "Chettinad 50", type: "image", link: "https://drive.google.com/file/d/1xTPZsbz2N16vSn0OwGWKCGmbJVfWrj5i/preview" },
  { title: "Chettinad 51", type: "image", link: "https://drive.google.com/file/d/1xvvRG52YxOhlPX-a-hkQvamZ3NHO8Ak3/preview" },
  { title: "Chettinad 52", type: "image", link: "https://drive.google.com/file/d/1zFfHXO50RTRgeTBZGAtjXghEXX_M6lmo/preview" },
  
  // Chettinad Video (4 Vertical, 1 Horizontal) - All from Google Drive
  { title: "Chettinad Video 1", type: "video", link: "https://drive.google.com/file/d/1zLp6NC3Mh6E0MDKy-KYa6E7WrZYYAl0H/preview" },
  { title: "Chettinad Video 2", type: "video", link: "https://drive.google.com/file/d/1LLBJina_W6RhTMYG37Vib9AfyqiOlBV9/preview" },
  { title: "Chettinad Video 3", type: "video", link: "https://drive.google.com/file/d/1RPT4UPGTj9dnXJfGSjrgBZVH9SGFTfgo/preview" },
  { title: "Chettinad Video 4", type: "video", link: "https://drive.google.com/file/d/1nljasKr4XInqPy8feC_h8_BCmX4MYID6/preview" },
  { title: "Chettinad Video 5", type: "video", link: "https://drive.google.com/file/d/1sDpZT-iBURxIGOktPaGxpAoxnqSsWpx_/preview" },

  // Teak Home (4 Vertical) - All from Google Drive
  { title: "Teakhome 1", type: "video", link: "https://drive.google.com/file/d/1Dg8mjQBOzznmC7AMTl5SL0vjHkMwRYAX/preview" },
  { title: "Teakhome 2", type: "video", link: "https://drive.google.com/file/d/1WhwqubTSVO8cZi_Z0cHJPRMlbcb8lH0R/preview" },
  { title: "Teakhome 3", type: "video", link: "https://drive.google.com/file/d/1ZwYN6LgQztAz_kBxx6UyJpZXp0APTb5U/preview" },
  { title: "Teakhome 4", type: "video", link: "https://drive.google.com/file/d/1bzqL1UrEC6kBXCShMmSFNnmfMQajTs-C/preview" },

  // Broadcast (2 Horizontal) - All from Google Drive
  { title: "Broadcast 1", type: "video", link: "https://drive.google.com/file/d/1TCjo5dc34mh1SUs-rgLD2tIYmb9CDfgp/preview" },
  { title: "Broadcast 2", type: "video", link: "https://drive.google.com/file/d/1wnobb3DVfskarqQC1_PLdt8kI6GUSL_w/preview" },

  // Independent (18 images from Google Drive)
  { title: "Independent 1", type: "image", link: "https://drive.google.com/file/d/11Hm5TvfAUbVC8xpmuoVyFjYjL2kBwdvL/preview" },
  { title: "Independent 2", type: "image", link: "https://drive.google.com/file/d/17k6Ws-Ex0VUqH1CEQ0MI5r7WkaDl2ULE/preview" },
  { title: "Independent 3", type: "image", link: "https://drive.google.com/file/d/1B3o-mNnl7pFH2IFcZiNw2NQI1abWoMU8/preview" },
  { title: "Independent 4", type: "image", link: "https://drive.google.com/file/d/1ESheKxsBB3dFdDC3cL3eiUQzltLmNXGO/preview" },
  { title: "Independent 5", type: "image", link: "https://drive.google.com/file/d/1I8aby-98S1NarKV7VyAO5UTohtmDhmXS/preview" },
  { title: "Independent 6", type: "image", link: "https://drive.google.com/file/d/1Mc_bCQwyzA9DwWs7OL3ry1_lSScOgV0S/preview" },
  { title: "Independent 7", type: "image", link: "https://drive.google.com/file/d/1PWlmb22eF2jVt4hPSge_eWUIhGAft5mP/preview" },
  { title: "Independent 8", type: "image", link: "https://drive.google.com/file/d/1Q9OWUuDU5oemDE8Eo8u_eppIEr1Egw7Q/preview" },
  { title: "Independent 9", type: "image", link: "https://drive.google.com/file/d/1V0oXMc_NN9_Dg_4uSfwKtvbstATFTeYI/preview" },
  { title: "Independent 10", type: "image", link: "https://drive.google.com/file/d/1XBRh_vgL_2YqtitvgyRXWb8FFl9yW_yX/preview" },
  { title: "Independent 11", type: "image", link: "https://drive.google.com/file/d/1YqYcHl8SWnAdkI9rWKFvnKXWj1dwGfvj/preview" },
  { title: "Independent 12", type: "image", link: "https://drive.google.com/file/d/1hmcvj3Yo9YcRnS6BdLFjvGCk6CR4SCj5/preview" },
  { title: "Independent 13", type: "image", link: "https://drive.google.com/file/d/1i2JdLusnGg9nLTlqaUvv3tWkvWIBlkfl/preview" },
  { title: "Independent 14", type: "image", link: "https://drive.google.com/file/d/1j1U8CkQTLWMdb19rVOhg9IGYqZxwP4rz/preview" },
  { title: "Independent 15", type: "image", link: "https://drive.google.com/file/d/1kLG7anbgcdyi2vtR-fP3cCmdERRrauUn/preview" },
  { title: "Independent 16", type: "image", link: "https://drive.google.com/file/d/1msT7f7E__uEu8Hxgerg2_EDDapF0-HMN/preview" },
  { title: "Independent 17", type: "image", link: "https://drive.google.com/file/d/1n-CWowqk-Gc4WRDsiEMK8y6jZVNt99fr/preview" },
  { title: "Independent 18", type: "image", link: "https://drive.google.com/file/d/1wHe0vA81lU0IG-MW7y8IjGBv4ak9c6X6/preview" }
];